"""
scripts/download_data.py
------------------------
ONE-TIME data acquisition script.  Run this once to populate data/raw/.
After this script completes successfully, you should not need to run it
again unless you want to extend the date range or re-download.

Steps performed:
  1. Download DONKI CME events   → data/raw/donki_cme_2015_2023.json
  2. Download DONKI solar flares → data/raw/donki_flr_2015_2023.json
  3. Download GFZ Kp 3-hourly   → data/raw/kp_3hr_2015_2023.csv
  4. Download OMNI 5-min .asc   → data/raw/omni_hro_modified/omni_5minYYYY.asc
  5. Build combined omni.csv    → data/raw/omni.csv  (replaces build_omni_csv.py)

Files generated by step 5 are stable — omni.csv only needs to be
rebuilt if you change the year range or the column selection in
omni_hro_parser._DEFAULT_KEEP_COLS.
"""
from __future__ import annotations

from src.config import Config
from src.io.downloaders import (
    build_omni_csv,
    download_donki_json_chunked,
    download_kp_from_complete_series_txt,
    download_omni_hro_modified_years,
)
from src.utils.logging_utils import get_logger

log = get_logger(__name__)


def main() -> None:
    cfg = Config()
    cfg.makedirs()

    start_year = cfg.start_year   # 2015
    end_year = cfg.end_year       # 2023
    start_date = f"{start_year}-01-01"
    end_date = f"{end_year}-12-31"

    log.info("=== Step 1/5  DONKI CME ===")
    r_cme = download_donki_json_chunked(
        activity="CME",
        start_year=start_year,
        end_year=end_year,
        out_json=cfg.donki_cme_file,
        timeout=240,
        sleep_s=0.6,
        overwrite=False,
    )
    log.info("CME → %s  (items=%s)", r_cme.saved_to, r_cme.n_rows)

    log.info("=== Step 2/5  DONKI FLR ===")
    r_flr = download_donki_json_chunked(
        activity="FLR",
        start_year=start_year,
        end_year=end_year,
        out_json=cfg.donki_flr_file,
        timeout=240,
        sleep_s=0.6,
        overwrite=False,
    )
    log.info("FLR → %s  (items=%s)", r_flr.saved_to, r_flr.n_rows)

    log.info("=== Step 3/5  Kp index ===")
    r_kp = download_kp_from_complete_series_txt(
        start_date=start_date,
        end_date=end_date,
        out_csv=cfg.kp_file,
        timeout=300,
        overwrite=False,   # Set True to force re-download
    )
    log.info("Kp  → %s  (rows=%s)", r_kp.saved_to, r_kp.n_rows)

    log.info("=== Step 4/5  OMNI HRO .asc files ===")
    omni_results = download_omni_hro_modified_years(
        years=range(start_year, end_year + 1),
        out_dir=cfg.omni_raw_dir,
        resolution="5min",
        overwrite=False,
    )
    for r in omni_results:
        log.info("  OMNI → %s", r.saved_to)

    log.info("=== Step 5/5  Build omni.csv from all .asc files ===")
    omni_csv_path = build_omni_csv(
        omni_raw_dir=cfg.omni_raw_dir,
        out_csv=cfg.omni_file,
        start_year=start_year,
        end_year=end_year,
        resolution="5min",
        overwrite=False,   # Set True to rebuild after changing column selection
    )
    log.info("OMNI CSV → %s", omni_csv_path)

    log.info("=== Download complete.  All raw data is in %s ===", cfg.raw_dir)
    log.info(
        "Next step: run  python -m scripts.run_eda  to build features and EDA figures."
    )


if __name__ == "__main__":
    main()